#!/usr/bin/env bash

LINT_STAGED_CONFIG='{"*.{js,yml}":"eslint --fix","*.hbs": "ember-template-lint --fix", "*.scss": "stylelint --fix"}'
STAGED_IN_DIRECTORY=$(git diff --name-only --cached | head -1 | cut -d "/" -f1)

if [ -n "$STAGED_IN_DIRECTORY" ]; then
  printf "\033[0;32m✔\033[0m Changed directory to /$STAGED_IN_DIRECTORY\n"
  cd $STAGED_IN_DIRECTORY && echo $LINT_STAGED_CONFIG | npx lint-staged -c -
fi
