SELECT *
FROM answers a
WHERE 1 = 1
  AND a.result <> 'ok'
  AND a."createdAt" :: DATE = '10/02/2022'
  AND a."challengeId" IN (
    'challenge1a6iZYNr8dJ0Ql');

select *
from sessions;
-- certification-candidate créé lors de l'import des candidats
-- certification-course créé lors du début du parcours (candidat)
-- assessments créé lors du début du parcours (questions à poser)
-- answers créé lors du parcours (réponses apportées)

select *
from assessments;
--
SELECT
    crt.name                                                                                   "centerName",
    s.id                                                                                       "sessionId",
    --cc."firstName",
    cc."userId",
    SUBSTRING(cc."firstName" FROM 1 FOR 3) || REPEAT('*', CHAR_LENGTH(cc."firstName") - 3 - 1) "firstNameAnon",
    --cc."lastName",
    SUBSTRING(cc."lastName" FROM 1 FOR 3) || REPEAT('*', CHAR_LENGTH(cc."lastName") - 3 - 1)   "lastNameAnon",
    --cc.birthdate,
    ans."createdAt"                                                                            "answeredAt",
    ans."challengeId",
    SUBSTRING(ans.result FROM 1 FOR 10);

-------------------------------------------------------------
------------ MEP
-------------------------------------------------------------


-- Réponses
select
    count(1)
--     "certification-courses"."id" as "certificationCourseId",
--     "answers"."challengeId"
from "sessions"
         inner join "certification-courses" on "certification-courses"."sessionId" = "sessions"."id"
         inner join "assessments" on "assessments"."certificationCourseId" = "certification-courses"."id"
         inner join "answers" on "answers"."assessmentId" = "assessments"."id"
where "answers"."result" <> 'ok'
  and "answers"."id" > 700064555
  and "answers"."id" < 701092524
  and "answers"."challengeId" = 'receQkwO1dvjQc2S3';


select
    count(1)
from (select DISTINCT
          "assessments"."id"
      from "sessions"
               inner join "certification-courses" on "certification-courses"."sessionId" = "sessions"."id"
               inner join "assessments" on "assessments"."certificationCourseId" = "certification-courses"."id"
               inner join "answers" on "answers"."assessmentId" = "assessments"."id"
      where "answers"."result" <> 'ok'
        and "answers"."id" > 700064555
        and "answers"."id" < 701092524
        and "answers"."challengeId" = 'receQkwO1dvjQc2S3'
      ORDER BY assessments.id ASC) t;


select
    "certification-courses"."id" as "certificationCourseId",
    "answers"."challengeId"
from "sessions"
         inner join "certification-courses" on "certification-courses"."sessionId" = "sessions"."id"
         inner join "assessments" on "assessments"."certificationCourseId" = "certification-courses"."id"
         inner join "answers" on "answers"."assessmentId" = "assessments"."id"
where "certification-courses"."createdAt"::DATE = '2022-02-10'
  and "answers"."result" <> 'ok'
  and "answers"."createdAt" between '2022-02-10 09:50:00.000000 +00:00' AND '2022-02-10 18:00:00.000000 +00:00'
  AND "answers"."challengeId" IN (
                                  'challenge1a6iZYNr8dJ0Ql',
                                  'challenge1bCcrUSiHEDdMy',
                                  'challenge1CaSmWYAMy3O9G',
                                  'challenge1DEHT8c3nr6kUO',
                                  'challenge1eKSJGm1XgGdQh',
                                  'challenge1entMzkopj7apB',
                                  'challenge1fUM2qrhHgZ8nz',
                                  'challenge1Gmne0NwTS6vRP',
                                  'challenge1hEgTZE61aDe5H',
                                  'challenge1HO6aZiU01w7ha',
                                  'challenge1HPPPHPcAFzevA',
                                  'challenge1kpKCmvL6jxxJV',
                                  'challenge1kyDrBtJOsxt7u',
                                  'challenge1M95jUR3ZREVob',
                                  'challenge1NNWUEWH0wWzQj',
                                  'challenge1nr37GJiCknahR',
                                  'challenge1P0n5KsIWNvjOy',
                                  'challenge1P6locYanfjBI7',
                                  'challenge1P61xaeuguZbA4',
                                  'challenge1QOIdpcyKn5Der',
                                  'challenge1qq28S0XUBGP3E',
                                  'challenge1rPyeKfRl2xgVn',
                                  'challenge1S2e22X2c5D0rK',
                                  'challenge1Sk1FTaQb8nX8o',
                                  'challenge1THlWZaFa7nEx8',
                                  'challenge1TJ9i3EE7NNPYW',
                                  'challenge1tluqHLhKTTu4N',
                                  'challenge1UUSXCUGnv6IdY',
                                  'challenge1uwX0TFeVfj7R2',
                                  'challenge1VbUyndcn9yMi2',
                                  'challenge1Wgw8mivCKsoUO',
                                  'challenge1wnL2wSzXNfuZa',
                                  'challenge1XKo9pc9sbNpo6',
                                  'challenge1xLwbNjGD4CuzJ',
                                  'challenge1XWtjTSlmtCVhg',
                                  'challenge1z4JS7BUOk0u18',
                                  'challenge1ZeTZZDOpUO65G',
                                  'challenge2A5Aq56bLL5C8I',
                                  'challenge2BvWMWHTvpxvVE',
                                  'challenge2h4zwY4LvUD9cb',
                                  'challenge2k03Y06VIDcC7G',
                                  'challenge2lBkS7IJhZuBbi',
                                  'challenge2LIhnCwc4xbHa1',
                                  'challenge2o9sVl5gvymFHc',
                                  'challenge2OLDrCqRPS28ZU',
                                  'challenge2On9xQKLPFF1js',
                                  'challenge2OnbLR38FgwXZe',
                                  'challenge2OSjCc79Z8vRwk',
                                  'challenge2qZjpSfqqgeA1w',
                                  'challenge2RseqPZiDCmSDt',
                                  'challenge2Rv2xwrdXqRm6w',
                                  'challenge2RxUgreQp9dJzz',
                                  'challenge2STd6Xahl0uORc',
                                  'challenge2swifWXSrgrjC0',
                                  'challenge2tXUvjNT1KKi1y',
                                  'challenge14pS5aO4SqyOAb',
                                  'challenge17aoyv5bnKAyHJ',
                                  'challenge17hxiRmq3At2b7',
                                  'challenge18NSod2dCfp7Y4',
                                  'challenge20LefVidI3XQTj',
                                  'challenge22v0hNBJJ2T0o6',
                                  'challenge23D6zQMZSjovbn',
                                  'challenge25nETyPRveuEwj',
                                  'challenge28bHlhuhiEqztI',
                                  'challenge28fYCb59jjbUdw',
                                  'challenge28kcEKUM4lQxYU',
                                  'challenge28kwuFJjZlaJs8',
                                  'challenge29HArQgxKtUXEC',
                                  'challenge29Mz5dh5tgT6w5',
                                  'challenge29P5GYfQVsCsEP',
                                  'challenge29r09MtItpRmJt',
                                  'challenge119QhseNBBjUgL',
                                  'challengeLmsw4d1fanvgB',
                                  'challengeMKtCMXVD1JKW0',
                                  'challengeOcUVlFtXZcFUP',
                                  'challengePB3rkXHbZrUqx',
                                  'challengePI8VdwE7PALa5',
                                  'challengePqQf3PDbIdsMv',
                                  'challengeQWMStWXu2fPwn',
                                  'challengeReuxqjGQ9514Y',
                                  'challengeWXglKwBwOJ3FV',
                                  'challengeX7fNQeTGHm43D',
                                  'challengeYmt6OA7drFjz5',
                                  'rec0gm0GFue3PQB3k',
                                  'rec0OytHOCNPlEd1a',
                                  'rec0pZ129MZ8nlj1u',
                                  'rec1AAmqgxG6XEYM5',
                                  'rec1aoHEOxWyiAEwM',
                                  'rec1bFrrPFEJzS5sR',
                                  'rec1BWDg2TD565Uze',
                                  'rec1cRaztawnuSyH0',
                                  'rec1cYAqfqO9TafU3',
                                  'rec1DoMTWB2aQDalS',
                                  'rec1DyGfpqu3qzBWj',
                                  'rec1EQqgGXiHZKbsO',
                                  'rec1eqY2rD1mQxfZf',
                                  'rec1g9HHDCjJuDO3x',
                                  'rec1HExlfBoer8fEW',
                                  'rec1JtS1zizIrEVrn',
                                  'rec1kequeffr5roaL',
                                  'rec1KLIyN4RbaY8js',
                                  'rec1kxiRD0noX6cvW',
                                  'rec1L1ZWbY344xdiu',
                                  'rec1lFQJfNdtozwcX',
                                  'rec1lVm1LAunxwqdo',
                                  'rec1lZCtQrj8FBXfd',
                                  'rec1n5HfHDOqyoJv2',
                                  'rec1NCa7wJXkglaJf',
                                  'rec1ngFxsfhDBQL0b',
                                  'rec1NQOOfcqUPLGlW',
                                  'rec1NR99Y9GPhFBXy',
                                  'rec1NTxS1UM62E4pa',
                                  'rec1Nv8Ma8vL65TKi',
                                  'rec1oRDK3R8zJ1exl',
                                  'rec1oysE0pwAuadic',
                                  'rec1ozwqzl731a3Ib',
                                  'rec1P3aBaznEbA3HR',
                                  'rec1P7R8BGf6bLaVn',
                                  'rec1qbOH61wDU7e0g',
                                  'rec1QGbakMQIJ3VlL',
                                  'rec1ql6fHDYyFs2GV',
                                  'rec1quCVj38nfiyIn',
                                  'rec1R3VENcH375EeL',
                                  'rec1rNvAVeG4NBZ5s',
                                  'rec1rtC2Yu8lHBCoh',
                                  'rec1rzgamqgysR2iY',
                                  'rec1S2dfouPamhIWZ',
                                  'rec1SaOjCSEfrUDyW',
                                  'rec1Sc7muPqoTYcY2',
                                  'rec1SfGChZEoGDj91',
                                  'rec1tcC1gFUhpQqaP',
                                  'rec1UKeDVFWDCH3ND',
                                  'rec1uqRqpsbYhZ6zP',
                                  'rec1V49vq2T6rksMJ',
                                  'rec1w2ccFL6PIhE7z',
                                  'rec1wg0v6gmp7kHqN',
                                  'rec1wmjzTWFwkNogO',
                                  'rec1Wv6Msk3q6NIGf',
                                  'rec1XIELCUQFakYqF',
                                  'rec1XUXAkZpgVW2c6',
                                  'rec1yNLjAXCFfJQcM',
                                  'rec1Z9Bxr0SuU7nVL',
                                  'rec1z9HjYtFsoAuxQ',
                                  'rec1za3Z1Xz9fw68m',
                                  'rec1zei6e4vQmyeeJ',
                                  'rec2aTH6tJVqurBJV',
                                  'rec2b1uoqgwUcr417',
                                  'rec2cDrNmu6GTtTs8',
                                  'rec2CLQNnAWlTvwUc',
                                  'rec2dRlifBTWLPvXn',
                                  'rec2dWJS14lJXQsVP',
                                  'rec2El2Ko6h2bzC03',
                                  'rec2gXbQ5Jn6unjCX',
                                  'rec2HfpOAgMTxR2jd',
                                  'rec2IWo1fY8rz7E0D',
                                  'rec2IwwKRNqdEfjyO',
                                  'rec2jIjTASD62EKHE',
                                  'rec2jNChTE2BtqLvU',
                                  'rec2lpWZaV2UYFiD8',
                                  'rec2LsmEepvK3GrLg',
                                  'rec2Lzr6l2jAYHyJw',
                                  'rec2mIMNJoq1t6cBs',
                                  'rec2NfkMA7ouSqQda',
                                  'rec2oe0RK5SKOe6xF',
                                  'rec2OGi8mjx5oOO1F',
                                  'rec2pJGpXkaUybmYN',
                                  'rec2RnYRt30vWUGFu',
                                  'rec2st8GxDejOE8Yf',
                                  'rec2sVNaRGK6yhRK7',
                                  'rec2UtJzahqriBzSK',
                                  'rec2VMe78VKuZOt5B',
                                  'rec2vmMkWBJbtStXx',
                                  'rec2W1PMYuXdUHYNq',
                                  'rec2wWjoprBvaZC4X',
                                  'rec2yhcF3tWbmS787',
                                  'rec3LFlDkpcjxTRxE',
                                  'rec3SCulLFeI7JWL7',
                                  'rec4JVai9gM3i1myk',
                                  'rec5uBBZC9FyAfIs7',
                                  'rec6mKVymknth0Heb',
                                  'rec6qcVEOmD3JNE8v',
                                  'rec7Z45UW9rFyyfVn',
                                  'rec7zCCUeaXCkg2JY',
                                  'rec8JElDsWS5HN1WI',
                                  'rec12MRwMkO97MhzN',
                                  'rec15Xi9Wh7Srgjq1',
                                  'rec17dhnoklHd5ASu',
                                  'rec20XAAFriWIdDmX',
                                  'rec22jeHuRNyMADTp',
                                  'rec22uDXIGqIIqlhb',
                                  'rec23CQ2j0X0TFCAG',
                                  'rec23OOePAXp3fx20',
                                  'rec23YpYMglAtCaUd',
                                  'rec24Imw7O5sHf4yF',
                                  'rec25fPz80M64Ha8M',
                                  'rec25lceSer8ri5TH',
                                  'rec26CczKildHDGe7',
                                  'rec26z2qcIyy4PP2Z',
                                  'rec29Dn0nqK2SOKal',
                                  'rec31cUurm3Gd3t5w',
                                  'rec42tMJI75pyathy',
                                  'rec79vwW3CEpiAO3Q',
                                  'rec172lEZUn5NqN0b',
                                  'rec177hdgaIS1304h',
                                  'rec212UVWOPqDbNW6',
                                  'rec213fDC4WLs9XBN',
                                  'rec255Vb4H8OjNHnE',
                                  'rec2595cEOp4Lo8Wd',
                                  'recajyseRdoWknb36',
                                  'recAPhwfW0qP8gdmD',
                                  'recaRDhriveS2ZFd3',
                                  'recatvE8qn3KTvJBc',
                                  'recaWBNYVJ2o3E83S',
                                  'recbNQNzafavdCRvR',
                                  'recbYuJ64Vh3aJWqO',
                                  'reccgGi0OkAamO4SG',
                                  'reccSTyklaDl2v2au',
                                  'recdfYfVS9nJ5Basz',
                                  'recE99QpC46Yug6nF',
                                  'recFDzf4iI0jQMcta',
                                  'recFjgyG30SNxu9iP',
                                  'recfwhCZxdlXR4QjH',
                                  'recFX0frUql7jgv7s',
                                  'recg1OfcXyRsl8Wzc',
                                  'recGABGElXqW6LXFu',
                                  'recHFQJhMceBvNOQP',
                                  'rechr1HEouh6wCceS',
                                  'reci23o146IsYMIlX',
                                  'recIY6yo3XAwVrhsh',
                                  'recJbpx7EnYs7GwBl',
                                  'recJFmiGxvO0FkGMf',
                                  'recjxqnAp8ue7ybyu',
                                  'reckfS9xi3v64Zle8',
                                  'recKhozPtS1kqYuZ0',
                                  'reckUuOFm0MbTR3NK',
                                  'recKXtnhhROzD66Rv',
                                  'recKZ0tl5Z3hYB1kJ',
                                  'recKzv8dy3hdCU4E3',
                                  'reclj6BGi9zuPEl4u',
                                  'recMEQC4MQKaCdhX',
                                  'recmh8Y8lKSSJVQLG',
                                  'recMKPArXuujUjK6',
                                  'recn7XhSDTWo0Zzep',
                                  'recnWiukhmsaVBGRs',
                                  'recOcT2Yaw4hnYez',
                                  'recOdhXmtkpytJWb',
                                  'recOGHRKlUFhUmmt2',
                                  'recOgnXcUuAf6m17U',
                                  'recouVNQT54dqYWuf',
                                  'recP0lgXplkOWPCDY',
                                  'recPsazSt1gWdRiU',
                                  'recpVHw8Rm3l7y1mS',
                                  'recPZEInhQAWHLnAb',
                                  'recQaWST2A8QBT2Cs',
                                  'recrAl2XR7QlFYE7i',
                                  'recrnODvfol4gSN6a',
                                  'recrTV4Ntp0qx4ENs',
                                  'recScoxxhxUVCN4oV',
                                  'recTNxABNnQSb5bfs',
                                  'recTRedcMwctjbmX',
                                  'recTSeULlMKKodFY',
                                  'recTZPeInbNwXzrac',
                                  'recUeaKlIBqmYk6j',
                                  'recVDDqehqAXw5EDO',
                                  'recVhOB99LYhci6a',
                                  'recVNUpTBrLssVJXu',
                                  'recVrkf7vtBzZ9Ig',
                                  'recwFJVbWFCbNqZGM',
                                  'recWiCwOvSkS9IY7n',
                                  'recWny4hZlJiQSvQ2',
                                  'recXlDCHTVcypz6oM',
                                  'recxzQDa7UnU3Glcs',
                                  'recYjHxGRJyc24vQP',
                                  'recyrdJPkElDYFDnx',
                                  'recyzCfaK2vOaehH4',
                                  'recZ48nRTrBoKpFZs',
                                  'recZDyYWe1tuF3L0g',
                                  'recZH8OrTfWvXLPD',
                                  'recZMu6IsXyAx0HJ',
                                  'recZStkrtLfDakgMS',
                                  'recZVmpmCSMBpxPzl'
    )
;


-- Neutralisation
SELECT
    cc.id,
    cc."courseId" "certificationCourseId",
    cc."challengeId",
    cc."isNeutralized",
    cc."updatedAt",
    'certification-challenges=>',
    cc.*
FROM "certification-challenges" cc
WHERE 1 = 1
  AND "updatedAt" BETWEEN '2022-02-14 13:00:00.000000 +00:00' AND '2022-02-14 14:00:00.000000 +00:00'
  AND cc."isNeutralized" IS TRUE
  AND cc."challengeId" IN (
                           'challenge1a6iZYNr8dJ0Ql',
                           'challenge1bCcrUSiHEDdMy',
                           'challenge1CaSmWYAMy3O9G',
                           'challenge1DEHT8c3nr6kUO',
                           'challenge1eKSJGm1XgGdQh',
                           'challenge1entMzkopj7apB',
                           'challenge1fUM2qrhHgZ8nz',
                           'challenge1Gmne0NwTS6vRP',
                           'challenge1hEgTZE61aDe5H',
                           'challenge1HO6aZiU01w7ha',
                           'challenge1HPPPHPcAFzevA',
                           'challenge1kpKCmvL6jxxJV',
                           'challenge1kyDrBtJOsxt7u',
                           'challenge1M95jUR3ZREVob',
                           'challenge1NNWUEWH0wWzQj',
                           'challenge1nr37GJiCknahR',
                           'challenge1P0n5KsIWNvjOy',
                           'challenge1P6locYanfjBI7',
                           'challenge1P61xaeuguZbA4',
                           'challenge1QOIdpcyKn5Der',
                           'challenge1qq28S0XUBGP3E',
                           'challenge1rPyeKfRl2xgVn',
                           'challenge1S2e22X2c5D0rK',
                           'challenge1Sk1FTaQb8nX8o',
                           'challenge1THlWZaFa7nEx8',
                           'challenge1TJ9i3EE7NNPYW',
                           'challenge1tluqHLhKTTu4N',
                           'challenge1UUSXCUGnv6IdY',
                           'challenge1uwX0TFeVfj7R2',
                           'challenge1VbUyndcn9yMi2',
                           'challenge1Wgw8mivCKsoUO',
                           'challenge1wnL2wSzXNfuZa',
                           'challenge1XKo9pc9sbNpo6',
                           'challenge1xLwbNjGD4CuzJ',
                           'challenge1XWtjTSlmtCVhg',
                           'challenge1z4JS7BUOk0u18',
                           'challenge1ZeTZZDOpUO65G',
                           'challenge2A5Aq56bLL5C8I',
                           'challenge2BvWMWHTvpxvVE',
                           'challenge2h4zwY4LvUD9cb',
                           'challenge2k03Y06VIDcC7G',
                           'challenge2lBkS7IJhZuBbi',
                           'challenge2LIhnCwc4xbHa1',
                           'challenge2o9sVl5gvymFHc',
                           'challenge2OLDrCqRPS28ZU',
                           'challenge2On9xQKLPFF1js',
                           'challenge2OnbLR38FgwXZe',
                           'challenge2OSjCc79Z8vRwk',
                           'challenge2qZjpSfqqgeA1w',
                           'challenge2RseqPZiDCmSDt',
                           'challenge2Rv2xwrdXqRm6w',
                           'challenge2RxUgreQp9dJzz',
                           'challenge2STd6Xahl0uORc',
                           'challenge2swifWXSrgrjC0',
                           'challenge2tXUvjNT1KKi1y',
                           'challenge14pS5aO4SqyOAb',
                           'challenge17aoyv5bnKAyHJ',
                           'challenge17hxiRmq3At2b7',
                           'challenge18NSod2dCfp7Y4',
                           'challenge20LefVidI3XQTj',
                           'challenge22v0hNBJJ2T0o6',
                           'challenge23D6zQMZSjovbn',
                           'challenge25nETyPRveuEwj',
                           'challenge28bHlhuhiEqztI',
                           'challenge28fYCb59jjbUdw',
                           'challenge28kcEKUM4lQxYU',
                           'challenge28kwuFJjZlaJs8',
                           'challenge29HArQgxKtUXEC',
                           'challenge29Mz5dh5tgT6w5',
                           'challenge29P5GYfQVsCsEP',
                           'challenge29r09MtItpRmJt',
                           'challenge119QhseNBBjUgL',
                           'challengeLmsw4d1fanvgB',
                           'challengeMKtCMXVD1JKW0',
                           'challengeOcUVlFtXZcFUP',
                           'challengePB3rkXHbZrUqx',
                           'challengePI8VdwE7PALa5',
                           'challengePqQf3PDbIdsMv',
                           'challengeQWMStWXu2fPwn',
                           'challengeReuxqjGQ9514Y',
                           'challengeWXglKwBwOJ3FV',
                           'challengeX7fNQeTGHm43D',
                           'challengeYmt6OA7drFjz5',
                           'rec0gm0GFue3PQB3k',
                           'rec0OytHOCNPlEd1a',
                           'rec0pZ129MZ8nlj1u',
                           'rec1AAmqgxG6XEYM5',
                           'rec1aoHEOxWyiAEwM',
                           'rec1bFrrPFEJzS5sR',
                           'rec1BWDg2TD565Uze',
                           'rec1cRaztawnuSyH0',
                           'rec1cYAqfqO9TafU3',
                           'rec1DoMTWB2aQDalS',
                           'rec1DyGfpqu3qzBWj',
                           'rec1EQqgGXiHZKbsO',
                           'rec1eqY2rD1mQxfZf',
                           'rec1g9HHDCjJuDO3x',
                           'rec1HExlfBoer8fEW',
                           'rec1JtS1zizIrEVrn',
                           'rec1kequeffr5roaL',
                           'rec1KLIyN4RbaY8js',
                           'rec1kxiRD0noX6cvW',
                           'rec1L1ZWbY344xdiu',
                           'rec1lFQJfNdtozwcX',
                           'rec1lVm1LAunxwqdo',
                           'rec1lZCtQrj8FBXfd',
                           'rec1n5HfHDOqyoJv2',
                           'rec1NCa7wJXkglaJf',
                           'rec1ngFxsfhDBQL0b',
                           'rec1NQOOfcqUPLGlW',
                           'rec1NR99Y9GPhFBXy',
                           'rec1NTxS1UM62E4pa',
                           'rec1Nv8Ma8vL65TKi',
                           'rec1oRDK3R8zJ1exl',
                           'rec1oysE0pwAuadic',
                           'rec1ozwqzl731a3Ib',
                           'rec1P3aBaznEbA3HR',
                           'rec1P7R8BGf6bLaVn',
                           'rec1qbOH61wDU7e0g',
                           'rec1QGbakMQIJ3VlL',
                           'rec1ql6fHDYyFs2GV',
                           'rec1quCVj38nfiyIn',
                           'rec1R3VENcH375EeL',
                           'rec1rNvAVeG4NBZ5s',
                           'rec1rtC2Yu8lHBCoh',
                           'rec1rzgamqgysR2iY',
                           'rec1S2dfouPamhIWZ',
                           'rec1SaOjCSEfrUDyW',
                           'rec1Sc7muPqoTYcY2',
                           'rec1SfGChZEoGDj91',
                           'rec1tcC1gFUhpQqaP',
                           'rec1UKeDVFWDCH3ND',
                           'rec1uqRqpsbYhZ6zP',
                           'rec1V49vq2T6rksMJ',
                           'rec1w2ccFL6PIhE7z',
                           'rec1wg0v6gmp7kHqN',
                           'rec1wmjzTWFwkNogO',
                           'rec1Wv6Msk3q6NIGf',
                           'rec1XIELCUQFakYqF',
                           'rec1XUXAkZpgVW2c6',
                           'rec1yNLjAXCFfJQcM',
                           'rec1Z9Bxr0SuU7nVL',
                           'rec1z9HjYtFsoAuxQ',
                           'rec1za3Z1Xz9fw68m',
                           'rec1zei6e4vQmyeeJ',
                           'rec2aTH6tJVqurBJV',
                           'rec2b1uoqgwUcr417',
                           'rec2cDrNmu6GTtTs8',
                           'rec2CLQNnAWlTvwUc',
                           'rec2dRlifBTWLPvXn',
                           'rec2dWJS14lJXQsVP',
                           'rec2El2Ko6h2bzC03',
                           'rec2gXbQ5Jn6unjCX',
                           'rec2HfpOAgMTxR2jd',
                           'rec2IWo1fY8rz7E0D',
                           'rec2IwwKRNqdEfjyO',
                           'rec2jIjTASD62EKHE',
                           'rec2jNChTE2BtqLvU',
                           'rec2lpWZaV2UYFiD8',
                           'rec2LsmEepvK3GrLg',
                           'rec2Lzr6l2jAYHyJw',
                           'rec2mIMNJoq1t6cBs',
                           'rec2NfkMA7ouSqQda',
                           'rec2oe0RK5SKOe6xF',
                           'rec2OGi8mjx5oOO1F',
                           'rec2pJGpXkaUybmYN',
                           'rec2RnYRt30vWUGFu',
                           'rec2st8GxDejOE8Yf',
                           'rec2sVNaRGK6yhRK7',
                           'rec2UtJzahqriBzSK',
                           'rec2VMe78VKuZOt5B',
                           'rec2vmMkWBJbtStXx',
                           'rec2W1PMYuXdUHYNq',
                           'rec2wWjoprBvaZC4X',
                           'rec2yhcF3tWbmS787',
                           'rec3LFlDkpcjxTRxE',
                           'rec3SCulLFeI7JWL7',
                           'rec4JVai9gM3i1myk',
                           'rec5uBBZC9FyAfIs7',
                           'rec6mKVymknth0Heb',
                           'rec6qcVEOmD3JNE8v',
                           'rec7Z45UW9rFyyfVn',
                           'rec7zCCUeaXCkg2JY',
                           'rec8JElDsWS5HN1WI',
                           'rec12MRwMkO97MhzN',
                           'rec15Xi9Wh7Srgjq1',
                           'rec17dhnoklHd5ASu',
                           'rec20XAAFriWIdDmX',
                           'rec22jeHuRNyMADTp',
                           'rec22uDXIGqIIqlhb',
                           'rec23CQ2j0X0TFCAG',
                           'rec23OOePAXp3fx20',
                           'rec23YpYMglAtCaUd',
                           'rec24Imw7O5sHf4yF',
                           'rec25fPz80M64Ha8M',
                           'rec25lceSer8ri5TH',
                           'rec26CczKildHDGe7',
                           'rec26z2qcIyy4PP2Z',
                           'rec29Dn0nqK2SOKal',
                           'rec31cUurm3Gd3t5w',
                           'rec42tMJI75pyathy',
                           'rec79vwW3CEpiAO3Q',
                           'rec172lEZUn5NqN0b',
                           'rec177hdgaIS1304h',
                           'rec212UVWOPqDbNW6',
                           'rec213fDC4WLs9XBN',
                           'rec255Vb4H8OjNHnE',
                           'rec2595cEOp4Lo8Wd',
                           'recajyseRdoWknb36',
                           'recAPhwfW0qP8gdmD',
                           'recaRDhriveS2ZFd3',
                           'recatvE8qn3KTvJBc',
                           'recaWBNYVJ2o3E83S',
                           'recbNQNzafavdCRvR',
                           'recbYuJ64Vh3aJWqO',
                           'reccgGi0OkAamO4SG',
                           'reccSTyklaDl2v2au',
                           'recdfYfVS9nJ5Basz',
                           'recE99QpC46Yug6nF',
                           'recFDzf4iI0jQMcta',
                           'recFjgyG30SNxu9iP',
                           'recfwhCZxdlXR4QjH',
                           'recFX0frUql7jgv7s',
                           'recg1OfcXyRsl8Wzc',
                           'recGABGElXqW6LXFu',
                           'recHFQJhMceBvNOQP',
                           'rechr1HEouh6wCceS',
                           'reci23o146IsYMIlX',
                           'recIY6yo3XAwVrhsh',
                           'recJbpx7EnYs7GwBl',
                           'recJFmiGxvO0FkGMf',
                           'recjxqnAp8ue7ybyu',
                           'reckfS9xi3v64Zle8',
                           'recKhozPtS1kqYuZ0',
                           'reckUuOFm0MbTR3NK',
                           'recKXtnhhROzD66Rv',
                           'recKZ0tl5Z3hYB1kJ',
                           'recKzv8dy3hdCU4E3',
                           'reclj6BGi9zuPEl4u',
                           'recMEQC4MQKaCdhX',
                           'recmh8Y8lKSSJVQLG',
                           'recMKPArXuujUjK6',
                           'recn7XhSDTWo0Zzep',
                           'recnWiukhmsaVBGRs',
                           'recOcT2Yaw4hnYez',
                           'recOdhXmtkpytJWb',
                           'recOGHRKlUFhUmmt2',
                           'recOgnXcUuAf6m17U',
                           'recouVNQT54dqYWuf',
                           'recP0lgXplkOWPCDY',
                           'recPsazSt1gWdRiU',
                           'recpVHw8Rm3l7y1mS',
                           'recPZEInhQAWHLnAb',
                           'recQaWST2A8QBT2Cs',
                           'recrAl2XR7QlFYE7i',
                           'recrnODvfol4gSN6a',
                           'recrTV4Ntp0qx4ENs',
                           'recScoxxhxUVCN4oV',
                           'recTNxABNnQSb5bfs',
                           'recTRedcMwctjbmX',
                           'recTSeULlMKKodFY',
                           'recTZPeInbNwXzrac',
                           'recUeaKlIBqmYk6j',
                           'recVDDqehqAXw5EDO',
                           'recVhOB99LYhci6a',
                           'recVNUpTBrLssVJXu',
                           'recVrkf7vtBzZ9Ig',
                           'recwFJVbWFCbNqZGM',
                           'recWiCwOvSkS9IY7n',
                           'recWny4hZlJiQSvQ2',
                           'recXlDCHTVcypz6oM',
                           'recxzQDa7UnU3Glcs',
                           'recYjHxGRJyc24vQP',
                           'recyrdJPkElDYFDnx',
                           'recyzCfaK2vOaehH4',
                           'recZ48nRTrBoKpFZs',
                           'recZDyYWe1tuF3L0g',
                           'recZH8OrTfWvXLPD',
                           'recZMu6IsXyAx0HJ',
                           'recZStkrtLfDakgMS',
                           'recZVmpmCSMBpxPzl'
    )
;

-- Scoring
SELECT *
FROM "assessment-results" asr
WHERE 1 = 1
--    AND asr.id = 100010
--    AND asr."assessmentId" = 100008
  AND "createdAt" BETWEEN '2022-02-14 13:00:00.000000 +00:00' AND '2022-02-14 14:00:00.000000 +00:00'
  AND emitter = 'PIX-ALGO-NEUTRALISATION'
;



select
    count(1)
--     "certification-courses"."id" as "certificationCourseId",
--     "answers"."challengeId"
from "sessions"
         inner join "certification-courses" on "certification-courses"."sessionId" = "sessions"."id"
         inner join "assessments" on "assessments"."certificationCourseId" = "certification-courses"."id"
         inner join "answers" on "answers"."assessmentId" = "assessments"."id"
         inner join "certification-challenges" cc
                    ON cc."courseId" = "certification-courses".id and cc."challengeId" = "answers"."challengeId"

where "answers"."result" <> 'ok'
  and "answers"."id" > 700064555
  and "answers"."id" < 701092524
  and "answers"."challengeId" = 'receQkwO1dvjQc2S3'
  and cc."isNeutralized" IS TRUE
;


select
    count(1)
from (select distinct
          sessions.id
      from "sessions"
               inner join "certification-courses" on "certification-courses"."sessionId" = "sessions"."id"
               inner join "assessments" on "assessments"."certificationCourseId" = "certification-courses"."id"
               inner join "answers" on "answers"."assessmentId" = "assessments"."id"
               inner join "certification-challenges" cc
                          ON cc."courseId" = "certification-courses".id and cc."challengeId" = "answers"."challengeId"

      where "answers"."result" <> 'ok'
        and "answers"."id" > 700064555
        and "answers"."id" < 701092524
        and "answers"."challengeId" = 'receQkwO1dvjQc2S3'
        and cc."isNeutralized" IS TRUE) a
;
