#!/bin/bash

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

[[ $current_branch = 'dev' ]] && {
 echo "You're trying to push to dev, whereas nominal workflow is to merge PR"
 echo "If you indeed need to do it, use git push --no-verify"
 exit 1
}

exit 0
