#!/bin/bash
PULL_REQUEST_NUMBER=$1
REVIEW_APP_NAME=pix-api-review-pr${PULL_REQUEST_NUMBER}
echo "Connecting to ${REVIEW_APP_NAME}, getting PostgreSQL URL"
scalingo env --app ${REVIEW_APP_NAME} | grep SCALINGO_POSTGRESQL_URL
